version: '3'
services:

  mongo:
    image: mongo:4.2
    container_name: test-mongo
    # security_opt:
    #   - seccomp:unconfined
    privileged: true
    command:
      - "numactl"
      - "--interleave=all"
      - "mongod"
      - "--bind_ip=0.0.0.0"
    volumes:
       - ./data/mongo:/data/db

  grip-kv:
    build: grip-kv
    container_name: test-grip-kv
    volumes:
        - ./configs/grip_kv_config.yml:/opt/grip_config.yml
        - ./grip-kv/load_kv.sh:/opt/load_kv.sh
        - ./data/grip-kv:/opt/db
        - ./timings:/opt/timings
        - $BMEGDATA:/data:ro
    entrypoint: ["grip", "server", "--config", "/opt/grip_config.yml"]
    ports:
      - 28201:8201
      - 28202:8202

  grip-mongo:
    image: bmeg/grip:latest
    container_name: test-grip-mongo
    volumes:
        - ./configs/grip_mongo_config.yml:/config/grip_config.yml
    entrypoint: ["grip", "server", "--config", "/config/grip_config.yml"]
    ports:
      - 18201:8201
      - 18202:8202
    depends_on:
      - mongo

  # python & go container for loading data, running tests, etc.
  etl:
    build: etl
    container_name: test-etl
    volumes:
      # mount bmeg-etl directory, to have access to `outputs/`
      - $BMEGDATA:/etl/bmeg-data
      # mount testing dir
      - $PWD:/etl
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs

  neo4j:
    build: neo4j
    container_name: test-neo4j
    volumes:
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j:/etl
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=250G
      - NEO4J_dbms_memory_heap_initial__size=25G
      - NEO4J_dbms_memory_heap_max__size=25G
      - NEO4J_dbms_active__database=bmeg_rc5.db
      # - NEO4J_dbms_active__database=bmeg_rc3.db
      # - NEO4J_dbms_active__database=bmeg.db
      # - NEO4J_dbms_active__database=reactome.db
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4J_dbms_auto__index_relationships_enabled=true
      # - NEO4J_dbms_auto__index_relationships_keys=gid
      # - NEO4J_dbms_auto__index_nodes_enabled=true
      # - NEO4J_dbms_auto__index_nodes_keys=gid

  # dgraph containers
  zero:
    image: dgraph/dgraph:latest
    container_name: test-dgraph-zero
    volumes:
      - ./data/dgraph/zero:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my zero:5080

  alpha:
    image: dgraph/dgraph:latest
    container_name: test-dgraph-alpha
    volumes:
      - ./data/dgraph/alpha:/dgraph
    ports:
      - 7080:7080
      - 8081:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my alpha:7080 --lru_mb 536871 --zero zero:5080

  ratel:
    image: dgraph/dgraph:latest
    container_name: test-dgraph-ratel
    ports:
      - 8000:8000
    command: dgraph-ratel
